domains:
  - host: tochka.appline.tw1.ru
    routes:
      - path: /app
        upstream: http://tochka-frontend:80
      - path: /admin
        upstream: http://tochka-admin:80
      - path: /api
        upstream: http://tochka-backend:8000
        strip_prefix: false

  - host: forever.appline.tw1.ru
    routes:
      - path: /app
        upstream: http://forever-frontend:80
      - path: /admin
        upstream: http://forever-admin:80
      - path: /api
        upstream: http://forever-backend:8000
        strip_prefix: false

  - host: portal.appline.tw1.ru
    routes:
      - path: /app
        upstream: http://portal-frontend:80

  - host: quiz10.appline.tw1.ru
    routes:
      - path: /app
        upstream: http://quiz10-frontend:80
      - path: /admin
        upstream: http://quiz10-admin:80
      - path: /api
        upstream: http://quiz10-backend:8000
        strip_prefix: false
