domains:
  - host: tochka.etalonfood.com
    routes:
      - path: /app
        upstream: http://tochka-frontend:80
      - path: /admin
        upstream: http://tochka-admin:80
      - path: /api
        upstream: http://tochka-backend:8000
        strip_prefix: false

  - host: forever.etalonfood.com
    routes:
      - path: /app
        upstream: http://forever-frontend:80
      - path: /admin
        upstream: http://forever-admin:80
      - path: /api
        upstream: http://forever-backend:8000
        strip_prefix: false
